import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const elements=new Map();
const el=id=>{if(!elements.has(id))elements.set(id,{id,hidden:false,value:'',style:{},setAttribute(){},getBoundingClientRect:()=>({left:0,top:0,width:390,height:844}),videoWidth:1920,videoHeight:1080});return elements.get(id);};
let settings={focusMode:'manual',focusDistance:1},calls=[],supported=true,rejectPoint=false,ignored=false;
const track={getCapabilities:()=>supported?{focusMode:['continuous','single-shot','manual'],focusDistance:{min:0,max:10,step:.1}}:{},getSettings:()=>settings,applyConstraints:async c=>{
 calls.push(c);const v=c.advanced?.[0]||Object.fromEntries(Object.entries(c).map(([k,v])=>[k,v.exact]));if(rejectPoint&&v.pointsOfInterest)throw Error('no point');if(ignored&&c.advanced)return;
 settings={...settings,...v};
}};
const context={navigator:{userAgent:'Android',mediaDevices:{getSupportedConstraints:()=>({pointsOfInterest:true})}},document:{getElementById:el,createElement:()=>({style:{}}),querySelector:s=>s==='.cameraAlternatives'?{prepend:b=>elements.set(b.id,b)}:null},setTimeout:(fn,ms)=>setTimeout(fn,ms===450?0:ms),clearTimeout,openCoinCamera:async()=>{},loadIdentifyPhoto:async()=>{},clearIdentifyPhoto:()=>{},setupCoinCameraControls:async()=>{},setCoinCameraFocus:async()=>{},coinCameraStream:null,coinCameraTrack:track,coinCameraDiagnostics:{focus_modes:['continuous','manual']},coinCameraFocusQueue:Promise.resolve()};
vm.createContext(context);vm.runInContext(await readFile('public/camera-entry.js','utf8'),context);
assert(await vm.runInContext('refocusAndroidCoin()',context));assert.equal(settings.focusMode,'single-shot','A tap sweep is not interrupted by a mode reset');assert.equal(calls[0].advanced[0].pointsOfInterest[0].x,.5);assert.equal(calls[0].advanced[0].focusMode,'single-shot');
assert(await vm.runInContext('refocusAndroidCoin({x:.5,y:.5},true)',context));assert.equal(settings.focusMode,'continuous','Opening enables continuous autofocus');
await vm.runInContext('setCoinCameraFocus(3)',context);assert.equal(settings.focusDistance,3);assert.equal(settings.focusMode,'manual');assert.match(el('coinCameraStatus').textContent,/Manual focus/);
await vm.runInContext('setupCoinCameraControls()',context);await context.coinCameraFocusQueue;assert.equal(el('coinCameraAutofocus').hidden,false);
const point=vm.runInContext('coinCameraSensorPoint(document.getElementById("coinCameraVideo"),0,422)',context);assert(point.x>.3&&point.x<.5);assert.equal(point.y,.5,'Cover preview is mapped back to the sensor');
const before=calls.length;el('coinCameraVideo').onpointerdown({isPrimary:true,pointerId:1,clientX:195,clientY:422});el('coinCameraVideo').onpointerup({pointerId:1,clientX:195,clientY:422});await context.coinCameraFocusQueue;assert(calls.length>before);
rejectPoint=true;assert(await vm.runInContext('refocusAndroidCoin()',context));assert.equal(settings.focusMode,'single-shot','Unsupported metering point falls back to a refocus request');assert.equal(context.coinCameraDiagnostics.tap_focus_verified,false);assert.match(el('coinCameraStatus').textContent,/tap position unsupported/);
ignored=true;settings.focusMode='manual';assert(await vm.runInContext('refocusAndroidCoin()',context));assert(calls.some(c=>c.focusMode?.exact==='single-shot'),'Ignored advanced mode retries exact constraints');
supported=false;const n=calls.length;assert.equal(await vm.runInContext('refocusAndroidCoin()',context),false);assert.equal(calls.length,n);await vm.runInContext('setupCoinCameraControls()',context);assert.equal(el('coinCameraAutofocus').hidden,true);
supported=true;rejectPoint=false;ignored=false;track.applyConstraints=async c=>{const v=c.advanced?.[0]||Object.fromEntries(Object.entries(c).map(([k,v])=>[k,v.exact]));settings={...settings,focusMode:v.focusMode};};
assert(await vm.runInContext('refocusAndroidCoin({x:.1,y:.2})',context));assert.equal(context.coinCameraDiagnostics.tap_focus_verified,false,'Accepted but ignored points must not be reported as set');assert.match(el('coinCameraStatus').textContent,/tap position unsupported/);
track.applyConstraints=async()=>{context.coinCameraTrack=null;};settings.focusMode='single-shot';await vm.runInContext('refocusAndroidCoin()',context);assert.equal(el('coinCameraStatus').textContent,'Requesting focus… Hold still.','Closed-camera jobs do not publish success');
console.log('PASS Android centre/tap autofocus, sensor coordinates, manual/auto return, point rejection, ignored constraints, unsupported hardware and stale track handling');
context.coinCameraTrack=track;settings={focusMode:'continuous',focusDistance:1};
track.applyConstraints=async c=>{const v=c.advanced?.[0]||Object.fromEntries(Object.entries(c).map(([k,v])=>[k,v.exact]));settings={...settings,...v};};
context.setTimeout=(fn,ms)=>setTimeout(fn,ms<=260?0:ms);
vm.runInContext('readAndroidFocusDetail=()=>coinCameraTrack.getSettings().focusDistance===4?100:30',context);
assert(await vm.runInContext('scanAndroidCoinFocus(coinCameraTrack,()=>true)',context));assert.equal(settings.focusDistance,4);assert.equal(settings.focusMode,'manual');assert.equal(context.coinCameraDiagnostics.detail_focus_scan.after,100);
settings={focusMode:'continuous',focusDistance:1};vm.runInContext('readAndroidFocusDetail=()=>30',context);
assert.equal(await vm.runInContext('scanAndroidCoinFocus(coinCameraTrack,()=>true)',context),false);assert.equal(settings.focusMode,'continuous','No measurable improvement restores autofocus');
settings={focusMode:'continuous',focusDistance:1};let current=true;context.isScanCurrent=()=>current;
track.applyConstraints=async c=>{settings={...settings,...c.advanced[0]};current=false;};
assert.equal(await vm.runInContext('scanAndroidCoinFocus(coinCameraTrack,isScanCurrent)',context),false,'Stale scan cannot publish or override a later focus choice');
const fixed={getSettings:()=>({deviceId:'wide'}),getCapabilities:()=>({focusMode:['none']})};let stopped=0;
context.oldStream={getVideoTracks:()=>[fixed],getTracks:()=>[{stop:()=>stopped++}]};context.newStream={getVideoTracks:()=>[track],getTracks:()=>[{stop(){}}]};
context.navigator.mediaDevices.enumerateDevices=async()=>[{kind:'videoinput',deviceId:'front',label:'Front camera'},{kind:'videoinput',deviceId:'main',label:'Back camera'}];let selected;
context.navigator.mediaDevices.getUserMedia=async options=>{selected=options.video.deviceId.exact;return context.newStream;};
vm.runInContext('androidCameraOpening=7',context);el('coinCamera').hidden=false;
assert.equal(await vm.runInContext('preferAndroidFocusLens(oldStream,null,7)',context),context.newStream);assert.equal(selected,'main');assert.equal(stopped,1);
assert.equal(await vm.runInContext('preferAndroidFocusLens(oldStream,"wide",7)',context),context.oldStream,'Explicit user lens is retained');
console.log('PASS detail-based focus scan, no-improvement restoration, stale scan cancellation and focusable rear-lens preference');
